### ISSUE TITLE
Restart not working if application was started with shell script

### ISSUE THREAD

**Issue by stephansann** [Dansoftowner/Restart4j#3]
Hi @Dansoftowner 

My application can be installed and started in two ways - via an installer or via downloading a ZIP file.
(See https://document-archiver.github.io/index.html#download)

When running the application from an installation, the restart works fine.

When running the application from the ZIP file (via shell script), the restart fails:

```
Exception in thread "Thread-3" com.restart4j.RestartException: Couldn't execute the starter command with the OS: [/usr/bin/java --module-path lib --module DocumentArchiver/com.sophisticatedapps.archiving.documentarchiver.Launcher]
	at Restart4j@1.4.1/com.restart4j.ApplicationRestart.execArray(ApplicationRestart.java:94)
	at Restart4j@1.4.1/com.restart4j.ApplicationRestart.exec(ApplicationRestart.java:82)
	at Restart4j@1.4.1/com.restart4j.ApplicationRestart.lambda$buildNewProcessCreation$4(ApplicationRestart.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Cannot run program "/usr/bin/java --module-path lib --module DocumentArchiver/com.sophisticatedapps.archiving.documentarchiver.Launcher": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at java.base/java.lang.Runtime.exec(Runtime.java:451)
	at Restart4j@1.4.1/com.restart4j.ApplicationRestart.execArray(ApplicationRestart.java:92)
	... 3 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 7 more
```

This is the shell script:
```
myMac2014:document-archiver-2.1.0-mac stephan$ cat DocumentArchiver.sh 
java --module-path lib --module DocumentArchiver/com.sophisticatedapps.archiving.documentarchiver.Launcher
```

**Comment by Dansoftowner** [comment]
Hi @stephansann , 

Thanks for reporting this issue! 
I will look into it! 

Best regards
Daniel

**Comment by stephansann** [comment]
Hi again, @Dansoftowner 

Just checked on Linux and there it works in both cases.
Seems to be a problem on macOS only.

Let me know if I can help you with input.

Best regards
Stephan

**Comment by stephansann** [comment]
Hi @Dansoftowner 

Any progress on this? Anything I could do from my side?

Just asking because I want to do a new release of my app soon, and it would be great to have a fixed restart in it 🤓

Thanks and best regards
Stephan

**Comment by Dansoftowner** [comment]
Hi @stephansann ,

Try this code:
```java
ApplicationRestart.builder().modifyCmd(cmd -> cmd.replaceAll("\\s+", "\00")).build().restartApp();
```

And let me know if it works or not!
Sorry for the late reply!

Best regards
Dsaniel

**Comment by Dansoftowner** [comment]
Hi @stephansann ,

Try this code:
```java
ApplicationRestart.builder().modifyCmd(cmd -> cmd.replaceAll("\\s+", "\00")).build().restartApp();
```

And let me know if it works or not!
Sorry for the late reply!

Best regards
Dsaniel

**Comment by stephansann** [comment]
Hi @Dansoftowner 

Nice! With this code it now works on macOS, started from ZIP-distribution.

The other five ways (three platforms, two distributions - the one above) I didn't test.
Let me know if you need that - I would have to build an installation package and fire up my VirtualBox.

Best regards
Stephan

**Comment by Dansoftowner** [comment]
Hi @stephansann , 

Well, on Windows it probably does not work, so I will make a new release soon :)

**Comment by stephansann** [comment]
Great - looking forward to it 😊

**Comment by Dansoftowner** [comment]
Check out version `1.4.4`!
If the problem is still present on MacOS, let me know!

Also, If you don't mind, please test it on Windows too (I already tested it on Linux).

**Comment by Dansoftowner** [comment]
Use the normal `ApplicationRestart.builder().build().restartApp()`.

**Comment by stephansann** [comment]
Hi @Dansoftowner 

Thanks for the new version.

Now the ZIP distribution version restarts correctly, but the installed version has a problem.

It's a problem with folders which have a blank in the name. I think we had this before, right!?

The installation folder is:
"/Applications/Document Archiver"

```
Exception in thread "Thread-10" com.restart4j.RestartException: Couldn't execute the starter command with the OS: [/Applications/Document, Archiver/DocumentArchiver.app/Contents/MacOS/JavaApplicationStub]
	at Restart4j@1.4.4/com.restart4j.CommandLineExecutor$MacOSExecutor.exec(CommandLineExecutor.java:70)
	at Restart4j@1.4.4/com.restart4j.ApplicationRestart.exec(ApplicationRestart.java:80)
	at Restart4j@1.4.4/com.restart4j.ApplicationRestart.lambda$buildNewProcessCreation$4(ApplicationRestart.java:72)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Cannot run program "/Applications/Document": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at java.base/java.lang.Runtime.exec(Runtime.java:451)
	at Restart4j@1.4.4/com.restart4j.CommandLineExecutor$MacOSExecutor.exec(CommandLineExecutor.java:68)
	... 3 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 7 more
```

**Comment by Dansoftowner** [comment]
I removed the previous command parsing strategy and updated OSHI in version `1.4.6`.
If the problem is still present, please let me know!

Thanks for your patience!

**Comment by stephansann** [comment]
With this version we are back to field 0 😕

When started from ZIP distribution, I once again get this:

```
Exception in thread "Thread-3" com.restart4j.RestartException: Couldn't execute the starter command with the OS: [/usr/bin/java --module-path lib --module DocumentArchiver/com.sophisticatedapps.archiving.documentarchiver.Launcher]
	at Restart4j@1.4.6/com.restart4j.CommandLineExecutor$MacOSExecutor.exec(CommandLineExecutor.java:69)
	at Restart4j@1.4.6/com.restart4j.ApplicationRestart.exec(ApplicationRestart.java:80)
	at Restart4j@1.4.6/com.restart4j.ApplicationRestart.lambda$buildNewProcessCreation$4(ApplicationRestart.java:72)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Cannot run program "/usr/bin/java --module-path lib --module DocumentArchiver/com.sophisticatedapps.archiving.documentarchiver.Launcher": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at java.base/java.lang.Runtime.exec(Runtime.java:451)
	at Restart4j@1.4.6/com.restart4j.CommandLineExecutor$MacOSExecutor.exec(CommandLineExecutor.java:67)
	... 3 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 7 more
```

**Comment by Dansoftowner** [comment]
Okay, so let me explain the problem.

In order to restart the application, Restart4j has to retrieve the command-line that started the app. 
Normally,on MacOS and Linux, this command line is delimited by null-chars (\00) that allows you to separate the arguments.

The bug is (probably in OSHI there is a problem) that if the app was started with shell script, this command is not delimited by null-chars, only by spaces. So if I split the command based on the spaces, I might get a wrong array (for example if the application folder has spaces in it's name like "Document Archiver").

So, until this bug is not solved, my solution for you is this:

In your MacOS shell script, pass an application argument for Document Archiver like `--mac-script` that indicates that the app was started with shell script:
```shell
java --module-path lib --module DocumentArchiver/com.sophisticatedapps.archiving.documentarchiver.Launcher --mac-script
```

Save the main-class app arguments:
```java
public class Launcher {

     private static List<String> arguments;

     public static void main(String[] args) {
           arguments = List.of(args);
           ....
     }

     public static List<String> getArguments() {
           return arguments;
     }
```

Then:
```java
ApplicationRestart.builder()
              .modifyCmd(cmd -> {
                       if (Launcher.getArguments().contains("--mac-script") {
                             return cmd.replaceAll("\\s+", "\00");
                        }
                        return cmd;
                }).build().restartApp();
```

It's just an example but I hope you got the point.
If you have any questions, tell me please!

I will keep in mind this issue and notify you when the issue is solved.

Best regards
Daniel

**Comment by stephansann** [comment]
Hi @Dansoftowner 

Okay - I see the problem. Thanks for the suggestion. I will implement something in this direction.

You say there may be a problem in OSHI. Are you going to open an issue for this or should I do that? (Even though you know the specifics better than I do.)

Thanks again and best regards
Stephan

**Comment by Dansoftowner** [comment]
Hi @stephansann , 

Don't worry, I will report the issue to the OSHI guys soon :) 

Best regards
Daniel

**Comment by stephansann** [comment]
Great.
For the time being I will have a look at the environment variables, which will reveal which way the app was started.
But I will be happy to remove this hack again as soon as possible.

Thanks for the always pleasant interaction 🙏🏻

If we ever meet on some kind of Java Conference (do you visit such?), we should have a beer together 😉

Best regards
Stephan

**Comment by dbwiddis** [comment]
OSHI maintainer here.  Found the bug. It's intermittent/unpredictable whether you'll get nulls or spaces, actually, so a better test of how to parse is whether there are any embedded nulls at all .... if not, assume it's spaces.

I'll have a fixed version of OSHI out this weekend.

**Comment by Dansoftowner** [comment]
Hi @dbwiddis ,

Thanks for your cooperation!

Yes, my first idea was your temporary solution ("check whether there are any embedded nulls at all .... if not, assume it's spaces"), but it's not reliable: if an executable's file path has spaces in it, I will get a wrong cmd-array.

For example:
The command line: `"/Applications/Document Archiver/DocumentArchiver.app/Contents/MacOS/JavaApplicationStub"`

Check it has nulls: **no**
So if I split it based on spaces, I get this:
`["/Applications/Document", "Archiver/DocumentArchiver.app/Contents/MacOS/JavaApplicationStub"]`

And it obviously won't work:
```
...
Caused by: java.io.IOException: Cannot run program "/Applications/Document": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at java.base/java.lang.Runtime.exec(Runtime.java:592)
	at java.base/java.lang.Runtime.exec(Runtime.java:451)
	at Restart4j@1.4.4/com.restart4j.CommandLineExecutor$MacOSExecutor.exec(CommandLineExecutor.java:68)
	... 3 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 7 more
```

**Comment by dbwiddis** [comment]
Yep. I agree parsing spaces is hard (if not impossible).  My suggestion was that if this is always used in a consistent manner (e.g., your own process) you might have more information about your own command line to help the parsing.   Alternately You could try to catch errors like the above and retry different parsing if it looks like a file path, etc...

All a pain... or wait for me to get out of a crazy busy work week and fix it properly in a few days. :)

**Comment by dbwiddis** [comment]
Alternately if you are on JDK 9+, you can use the `ProcessHandle` API to get the value correctly.

**Comment by Dansoftowner** [comment]
Thank you for the advices! 

We will wait for your bug fix, no problem;).
 
Thanks for your work.

**Comment by dbwiddis** [comment]
FYI, I've just released OSHI 5.7.4 with this fix.

**Comment by stephansann** [comment]
@dbwiddis Great - thanks a lot for that 🙏🏻

@Dansoftowner let me know if/when I can help you testing on Mac 🤓

A nice evening to both of you 🍀

**Comment by dbwiddis** [comment]
@stephansann you should be able to place the `oshi-core` dependency in your own dependency manager config (`build.gradle` or `pom.xml`) and it should override the transient dependency in Restart4J.  So you could test now without waiting for Restart4j to update.

**Comment by stephansann** [comment]
@dbwiddis Thanks for the suggestion. But AFAIR Daniel already tried to include workarounds in his code for the problem. So just exchanging the the OSHI version may not do the trick and may even end up in unexpected results. But as I know Daniel he is very quick with new versions, so I'll wait for that.

**Comment by dbwiddis** [comment]
@stephansann The workarounds were for having spaces instead of nulls.  This issue mentions being started by a script, but in actuality the underlying bug was random (improperly byte sized values on the native stack), so any patterns you detected were not consistent.

`oshi-core` version 5.7.4 will only have nulls so there are no workarounds needed.  (Actually the bug was introduced in 5.3.7 so versions 5.3.6 and earlier should also be safe.) Unless one of the workarounds assumes spaces when there are actually nulls, it should work.   In that case, reverting to the version of Restart4J just before the workarounds, plus the newest OSHI, should work.

**Comment by Dansoftowner** [comment]
@stephansann Check out version `1.4.7`! :)

**Comment by stephansann** [comment]
Hi @Dansoftowner 

Thanks a lot for the quick implementation.

I now included it in Document Archiver and it works for both "startup ways" 🎉

BTW had to exclude the old OSHI version in jSystemThemeDetector to make it work. So maybe you could update it there, too!?

@dbwiddis - sorry I wasn't able to answer your post yesterday evening, had to go. Anyhow this is fixed now (at least for Big Sur (I hope we don't have a problem with older macOS versions now 😬)).

Both of you have a great start into the new week 🍀

Best regards
Stephan
